name: Test for Golang

on: [ push, pull_request ]

jobs:
  unix-tests:
    name: Test on ${{ matrix.os }} with Golang ${{ matrix.go-version }}
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        go-version: [ '^1.17' ]
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build Golang
        run: |
          ls
          go mod download
          go run build -o main main.go
      - name: Run Test
        run: ./main hyperf/hyperf